### ISSUE TITLE
use format --write

### ISSUE THREAD

**Issue by oguilleux** [skrulling/vite-plugin-biome#1]
Hi ! Love the plugin idea !

The discussion tab is not actived on this repo so I'll be glad to move this "issue" to a proper discussion :)

I'd like to be able to also use the command format like so `biome format --write ./my/custom/path`.

- You seem to use only the lint command.
- I think it'd be great to add the options in the documentation (lintPaths)
- Also does this provide on reload biome command ?

Opened to talk about it

**Comment by skrulling** [comment]
This feature has now been added. Thanks for the suggestion @oguilleux 🙌
