### ISSUE TITLE
`applyFixes` option uses deprecated `--apply` flag

### ISSUE THREAD

**Issue by vaquilina-work** [skrulling/vite-plugin-biome#9]
Since [1.8.0](https://github.com/biomejs/biome/blob/main/CHANGELOG.md#cli-3), biome CLI options `--apply` and `--apply-unsafe` are deprecated and will be removed in the next major release. They have been replaced by `--write` & `--write-unsafe`.

**Comment by skrulling** [comment]
Fixed

**Comment by vaquilina-work** [comment]
@skrulling thank you!
